/**
 * Updates WorkoutMaster rows with MET values for calorie calculation.
 * Formula: caloriesBurned = met × user.weight (kg) × durationMinutes × 0.0175
 *
 * Run from backend/: npx ts-node scripts/seed-workout-master-met.ts
 * Requires: DATABASE_URL and migration 20260308120000 (WorkoutMaster.met column) applied.
 */

import prisma from '../src/config/database';

const MET_VALUES: [string, number][] = [
  ['Generic Workout', 6],
  ['Workout', 6],
  ['General Workout', 6],
  ['Gym Workout', 6],
  ['Machine Workout', 7],
  ['Machine Workout Misc.', 6],
  ['Weight Workout', 6],
  ['Total Body Weights', 6],
  ['Total Body Other', 6],
  ['General Total Body', 6],
  ['Mat Workout', 6],
  ['Home Workout', 6],
  ['Health Club', 7],
  ['Gym Misc.', 6],
  ['General Strength Training', 6],
  ['Lower Body', 6],
  ['Upper Body', 6],
  ['Upper Body with Weights Other', 6],
  ['Lower Body with Weights Other', 6],
  ['Chest with Weights Other', 6],
  ['Shoulders', 6],
  ['Shoulders with Weights Other', 6],
  ['Forearms with Weights Other', 6],
  ['Abdominals', 6],
  ['Abs', 6],
  ['Abs Video', 6],
  ['Biceps', 6],
  ['Triceps with Weights Other', 6],
  ['Legs', 6],
  ['Kettlebell', 6],
  ['Barre Workout', 5.5],
  ['Pure Barre', 5.5],
  ['Body Pump', 7],
  ['CrossFit Class', 10],
  ['CrossFit Video', 10],
  ['Orangetheory', 9],
  ['HIIT', 9],
  ['Tabata', 10],
  ['Insanity', 10],
  ['Fit Body Boot Camp', 6],
  ['Gym Intervals', 6],
  ['Cardiovascular (CV) Circuit Training', 7],
  ['Resistance Circuit Training', 7],
  ['Circuit Training', 7],
  ['Aerobic', 7],
  ['Aerobics', 7],
  ['Step Aerobics Class', 7],
  ['Spinning Class', 8],
  ['Spin', 8],
  ['Jump Rope', 10],
  ['Stair Machine', 8],
  ['Climbing Stairs Running', 8],
  ['Rowing', 7],
  ['Rowing Machine', 7],
  ['Elliptical Machine', 6],
  ['Elliptical Bike', 6],
  ['Incline Trainer', 7],
  ['Stationary Bike', 6],
  ['Indoor Bike', 6],
  ['Indoor Bike Trainer', 6],
  ['Cross Trainer', 7],
  ['Walk', 4.5],
  ['General Walk', 4.5],
  ['Power Walk', 5],
  ['Casual Walk', 3.5],
  ['Quick Walking', 4.5],
  ['Long Walk', 4.5],
  ['Brisk Walk', 5],
  ['Interval Walk', 5],
  ['Family Walk', 3.5],
  ['Group Walk', 3.5],
  ['Dog Walk', 3.5],
  ['Treadmill Walk', 4.5],
  ['Indoor Track Walk', 4],
  ['Hike', 6],
  ['General Hike', 6],
  ['Hiking Light or No Pack', 6],
  ['Hiking Medium Pack', 7],
  ['Hiking Heavy Pack', 9],
  ['Trekking', 6],
  ['Stairs', 5],
  ['Climbing Stairs Walking', 5],
  ['Climbing Stairs Indoor Walking', 5],
  ['Single Stroller Walk', 4],
  ['Double Stroller Walk', 4],
  ['Carrying Child Walk', 4],
  ['Run', 8.4],
  ['General Run', 8.4],
  ['Quick Run', 9],
  ['Long Run', 9],
  ['Trail Run', 9],
  ['Easy Jog', 7],
  ['Indoor Run / Jog', 8],
  ['Indoor Track Run', 8],
  ['Treadmill Run', 8],
  ['Interval Run', 10],
  ['Run Race / Event', 10],
  ['Dog Run', 8],
  ['Group Run', 8],
  ['Bike Ride', 5.8],
  ['Cycling', 5.8],
  ['Biking', 5.8],
  ['Road Cycling', 7],
  ['General Road Cycling', 6],
  ['Road Cycling Indoor', 7],
  ['Hybrid Cycling', 6],
  ['General Hybrid Cycling', 6],
  ['Mountain Biking', 8],
  ['General Mountain Biking', 8],
  ['Mountain Biking Long Distance', 9],
  ['Downhill Mountain Biking', 8],
  ['Track Cycling', 8],
  ['Indoor Bike Ride', 7],
  ['Electric Bicycle', 4],
  ['Swim', 6],
  ['Indoor Swim', 6],
  ['Lap Swim', 7],
  ['General Lap Swim', 7],
  ['Open Water Swim', 7],
  ['Group Swimming', 6],
  ['Swimming Lessons', 5],
  ['Swim Class / Aerobics', 6],
  ['Football', 7],
  ['Football Competitive', 8],
  ['Football Practice', 6],
  ['Soccer Sport', 7],
  ['Indoor Soccer', 7],
  ['Futsal', 8],
  ['Basketball', 8],
  ['Cricket', 5],
  ['Indoor Cricket', 5],
  ['Volleyball', 4],
  ['Indoor Volleyball', 4],
  ['Beach Volleyball', 8],
  ['Field Hockey', 8],
  ['Handball', 7],
  ['Tennis', 8],
  ['Tennis Doubles', 7],
  ['Badminton', 6],
  ['Squash', 9],
  ['PickleBall', 5],
  ['Racquetball', 8],
  ['Table Tennis', 4],
  ['Rock Climbing', 8],
  ['Rock Climbing Outdoor', 8],
  ['Mountaineering', 9],
  ['Skiing', 7],
  ['Snorkelling', 5],
  ['Kayak', 5],
  ['Whitewater Rafting', 7],
  ['Adventure Race / Event', 9],
  ['Stand Up Paddling', 6],
  ['Motorcycle', 2],
  ['Sports Conditioning', 7],
  ['Dance', 6],
  ['Dance Class', 6],
  ['Indoor Dance', 6],
  ['Classical Dance', 5],
  ['Latin Dance', 7],
  ['Zumba', 8],
  ['Strong by Zumba', 8],
  ['Yoga', 3],
  ['Yoga Class', 3],
  ['Yoga General', 3],
  ['Power Yoga', 5],
  ['Ashtanga Yoga', 5],
  ['CorePower Yoga', 5],
  ['Stretch / Sculpt', 2.5],
  ['Meditation', 1.5],
  ['Recovery', 2],
  ['Yard Work', 4],
  ['Gardening', 4],
  ['Farming', 5],
  ['Cleaning (Light)', 3],
  ['House Work', 3],
  ['Misc Tasks (Light)', 3],
  ['Vacuuming', 3.5],
  ['Golf', 4],
  ['Singing', 2],
  ['Trampoline', 4],
];

function escapeSqlString(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  const valuesClause = MET_VALUES.map(
    ([workoutType, met]) => `('${escapeSqlString(workoutType)}', ${met})`
  ).join(',\n  ');

  const sql = `
UPDATE "WorkoutMaster" wm
SET "met" = v.met
FROM (
  VALUES
  ${valuesClause}
) AS v("workoutType", "met")
WHERE wm."workoutType" = v."workoutType"
  `.trim();

  const count = await prisma.$executeRawUnsafe(sql);
  console.log('Updated WorkoutMaster.met for', count, 'rows.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
